#!/bin/bash

set -eu
date

dir=$(cd $(dirname $0); pwd)
from=$dir/apex/getObjectAPIName
to=$(mktemp)
function rm_tmpfile {
  [[ -f "$tmpfile" ]] && rm -f "$tmpfile"
}
# 正常終了したとき
trap rm_tmpfile EXIT
# 異常終了したとき
trap 'trap - EXIT; rm_tmpfile; exit -1' INT PIPE TERM


echo $from
cat $from |sed -e 's/__OBJECT_NAME__/$1/g' > $to
sfdx force:data:apex:execute --apexcodefile $to

