#!/bin/bash
set -eu

to=$(mktemp)
function rm_tmpfile {
  [[ -f "$to" ]] && rm -f "$to"
}
# 正常終了したとき
trap rm_tmpfile EXIT
# 異常終了したとき
trap 'trap - EXIT; rm_tmpfile; exit -1' INT PIPE TERM

dir=$(cd $(dirname $0); pwd)
if [ $# -eq 0 ]; then
        echo "  getObjectInfo {-l | -c | -i } "
        echo "    : API名を取得する。"
        echo "    : -l:API名のみ列挙する"
        echo "    : -c:API名のみCSV形式で表示する。＊最終カラムに余計なカンマがつく"
        echo "    : -i:情報つきで列挙する"
  exit 1;
fi

for OPT in "$@"
do
  case $OPT in

    -l ) 
        from=$dir/apex/getObjectAPIName
        obj=$2
        shift 2
        ;;
    -c ) 
        from=$dir/apex/getCSVformatData
        obj=$2
        shift 2
        ;;
    -i ) 
        from=$dir/apex/getObjectInfo
        obj=$2
        shift 2
        ;;

     -h)
        echo "  getObjectInfo {-l | -c | -i } "
        echo "    : API名を取得する。"
        echo "    : -l:API名のみ列挙する"
        echo "    : -c:API名のみCSV形式で表示する。＊最終カラムに余計なカンマがつく"
        echo "    : -i:情報つきで列挙する"
        shift 2
        ;;
    --) shift 
        exit 2 ;;
  esac
done   
cat $from |sed -e "s/__OBJECT_NAME__/$obj/g" > $to
sfdx force:apex:execute --apexcodefile $to |grep USER_DEBUG | sed -e 's/.*|DEBUG|//g' | sed 's/\¥n/\'$'\n/g'

