#!/bin/bash
set -eu

to=$(mktemp)
function rm_tmpfile {
  [[ -f "$to" ]] && rm -f "$to"
}
# 正常終了したとき
trap rm_tmpfile EXIT
# 異常終了したとき
trap 'trap - EXIT; rm_tmpfile; exit -1' INT PIPE TERM

dir=$(cd $(dirname $0); pwd)
from=$dir/apex/getObjectInfo

cat $from |sed -e "s/__OBJECT_NAME__/$1/g" > $to
sfdx force:apex:execute --apexcodefile $to |grep USER_DEBUG | sed -e 's/.*|DEBUG|//g'

