#!/bin/bash

#####slack.confの中身実行フォルダにCONFを配置する。
#####ここから#####
# WebHookのURL
# URL='https://hooks.slack.com/services/XXXXXXXXXXXXX'
# 送信先のチャンネル
# CHANNEL=${CHANNEL:-'#app_test'}
# 絵文字
# EMOJI=${EMOJI:-':sushi:'}
# 見出し
# HEAD=${HEAD:-"midashi\n"}
#####ここまで#####
. ./slack.conf

set -eu

if [ $# -ne 2 ]; then
	UNAME="BOT"
else
	UNAME="[ $1 ] $2 "
fi

# パイプの有無
if [ -p /dev/stdin ]; then
	tmp=$(mktemp)
	# MESSAGE=`cat - | sed -e "s/\"/\'/g" | perl -p -e "s/\n/\\n/" |sed -e 's/\\/\\\\/g'`
	cat - |sed -e 's/─/-/g'| sed -e "s/\"/\'/g" |sed -e 's/\\/\\\\/g' | perl -p -e "s/\n/\\n/"  >>$tmp
	MESSAGE=`cat $tmp`
	echo $MESSAGE 
	rm $tmp
else
	echo "nothing stdin"
	exit 1
fi

# json形式に整形
payload="payload={
	\"username\": \"$UNAME\",
	\"icon_emoji\": \"${EMOJI}\",
	\"text\": \"$MESSAGE\",
	\"fallbcack\": \"$UNAMEがツイートしました。\"
	,\"attachments\":[{\"text\":\"\"}]
}"

tmpfile=$(mktemp)
echo $payload >> $tmpfile
cat $tmpfile > ./tmp.json

# 送信
 curl -s -S -X POST --data-URLENCODE "${payload}" ${URL}
rm $tmpfile
