#!/bin/bash

#####slack.confの中身実行フォルダにCONFを配置する。
#####ここから#####
# WebHookのURL
# URL='https://hooks.slack.com/services/XXXXXXXXXXXXX'
#####ここまで#####
. ./slack.conf

set -eu

if [ $# -ne 2 ]; then
	UNAME="[:sushi:BOT]"
else
	UNAME="[ $1 ] $2 "
fi

# パイプの有無
if [ -p /dev/stdin ]; then
	tmp=$(mktemp)
	# MESSAGE=`cat - | sed -e "s/\"/\'/g" | perl -p -e "s/\n/\\n/" |sed -e 's/\\/\\\\/g'`
	cat - |sed -e 's/─/-/g'| sed -e "s/\"/\'/g" |sed -e 's/\\/\\\\/g' | perl -p -e "s/\n/\\n/"  >>$tmp
	MESSAGE=`cat $tmp`
	echo $MESSAGE 
	rm $tmp
else
	echo "nothing stdin"
	exit 1
fi

# json形式に整形
payload="payload={
	\"text\": \"$UNAME\n$MESSAGE\"
}"

tmpfile=$(mktemp)
echo $payload >> $tmpfile
cat $tmpfile > ./tmp.json

# 送信
 curl -s -S -X POST --data-URLENCODE "${payload}" ${URL}
rm $tmpfile
