#!/bin/bash

set -eu
echo "start sfdx force:apex:log:tail | grep -e "FATAL" -e ": line""
echo "`date`------------------------------------------"
while : ;do sfdx force:apex:log:tail | grep -e "FATAL" -e ": line";done
