#!/bin/bash
set -eu

LOGTYPE='USER_DEBUG'
if [ $# -eq 0 ]; then
echo "  sfTraceFlagCreate {-d ”SFDC_DevConsole”} {-N ”<ユーザ名>” | -i ”<ユーザID>”} "
echo "    : -d <デバッグレベル名>:[設定]-[デバッグログ]画面から確認できる「デバッグレベル名」、もしくは[新しいデバッグレベル]画面で設定した「名前」"
echo "    : -N ”<ユーザ名>”:ユーザ名　User.Name"
echo "    : -i  -i ”<ユーザID>”:ユーザId　User.Id" 
  exit 1;
fi

for OPT in "$@"
do
  case $OPT in

    -d ) 
        if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
            echo "$PROGNAME: option requires an argument -- $1" 1>&2
            exit 1
        fi
        DLID=`sfGetDebugLevelId -d $2`
        shift 2
        ;;
            
    -i )
        if [[ -z "$1" ]] || [[ "$2" =~ ^-+ ]]; then
            echo "$PROGNAME: option requires an argument -- $1" 1>&2
            exit 1
        fi 
        ID=`sfdx force:data:soql:query -q "select id from User where Id='$2'"  -r csv| tail -1 `;;
    -N )
        if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
            echo "$PROGNAME: option requires an argument -- $1" 1>&2
            exit 1
        fi
        ID=`sfdx force:data:soql:query -q "select id from User where Name='$2'" -r csv| tail -1 `;;
    -h )
echo "  sfTraceFlagCreate {-d ”SFDC_DevConsole”} {-N ”<ユーザ名>” | -i ”<ユーザID>”} "
echo "    : -d <デバッグレベル名>:[設定]-[デバッグログ]画面から確認できる「デバッグレベル名」、もしくは[新しいデバッグレベル]画面で設定した「名前」"
echo "    : -N ”<ユーザ名>”:ユーザ名　User.Name"
echo "    : -i  -i ”<ユーザID>”:ユーザId　User.Id"
shift 2;;
    --) shift 
        exit 2 ;;
  esac
done

START=`date -u "+%Y-%m-%dT%H:%M:%S.000+0000"`
sfdx force:data:record:create -t -s TraceFlag -v "DebugLevelId=$DLID StartDate=$START ExpirationDate='' LogType=$LOGTYPE TracedEntityId=$ID"

exit 0;