#!/bin/bash
set -eu

if [ $# -ne 4 ]; then
  echo "指定された引数は$#個です。" 1>&2
  echo "実行するには4個の引数が必要です。" 1>&2
  exit 1;
fi
LOGTYPE='USER_DEBUG'
echo $@

for OPT in "$@"
do
  case $OPT in
 #   -t ) 
 #       if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
 #           echo "$PROGNAME: option requires an argument -- $1" 1>&2
 #           exit 1
 #       fi
 #       LOGTYPE=$2
    -d ) 
    echo $2
        if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
            echo "$PROGNAME: option requires an argument -- $1" 1>&2
            exit 1
        fi
        DLID=`sfGetDebugLevelId $2`
        shift 2
        ;;
            
    -i )
        if [[ -z "$1" ]] || [[ "$2" =~ ^-+ ]]; then
            echo "$PROGNAME: option requires an argument -- $1" 1>&2
            exit 1
        fi 
        ID=`sfdx force:data:soql:query -q "select id from User where Id='$2'"  -r csv| tail -1 `;;
    -N )
    echo $2
        if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
            echo "$PROGNAME: option requires an argument -- $1" 1>&2
            exit 1
        fi
        ID=`sfdx force:data:soql:query -q "select id from User where Name='$2'" -r csv| tail -1 `;;

    --) shift 
        exit 2 ;;
  esac
done


START=`date -u "+%Y-%m-%dT%H:%M:%S.000+0000"`
sfdx force:data:record:create -t -s TraceFlag -v "DebugLevelId=$DLID StartDate=$START ExpirationDate='' LogType=$LOGTYPE TracedEntityId=$ID"

exit 0;